<?php
return [
    'label'=>'Etiqueta',
    'description'=>'Descripción',
    'unit_price'=>'Precio Unitario',
    'units'=>'Cantidad de unidades',
    'comission'=>'Comisión',
    'unit_type'=>'Tipo de unidad',
    'provider_id'=>'Proveedor',
    'client_id'=>'Cliente',
    'name'=>'Nombre',
    'address'=>'Dirección',
    'contact_name'=>'Nombre de Contacto',
    'email'=>'Email',
    'phone'=>'Teléfono',
    'category'=>'Categoría',
    'amount'=>'Monto',
    'type'=>'Tipo',
    'reference'=>'Referencia',
    'invoice_id'=>'Cotización',
    'cash'=>'Efectivo',
    'transfer'=>'Transferencia',
    'check'=>'Cheque',
    'pending'=>'Pendiente',
    'completed'=>'Completada',
];