const strings = {
        format_date: "Fecha",
        client:"Cliente",
        project:"Proyecto",
        name:"Nombre",
        description:"Descripción",
        label:"Concepto",
        amount:"Monto",
        amount_final:"Monto Final",
        comission:"Comisión",
        "Next &raquo;":"Siguiente >",
        "&laquo; Previous":"< Anterior",
        pending:"Pendiente",
        completed:"Completado",
        rejected:"Rechazado",
        address:"Dirección",
        phone:"Teléfono",
        contact_name:"Nombre de Contacto",
        units:"Unidades",
        unit_price:"Valor Unitario",
        total_comission:"Total con comisión",
        required:'Este campo es requerido',
        delete:"Borrar",
        cancel:"Cancelar",
        client_id:"Client",
        contact_name:"Nombre de contacto",
        phone:"Teléfono",
        email:"Email",
        category:"Categoría"
};
export default strings;