const strings = {
        format_date: "Fecha",
        client:"Cliente",
        project:"Proyecto",
        name:"Nombre",
        description:"Descripción",
        label:"Concepto",
        amount:"Monto",
        amount_final:"Monto Final",
        comission:"Comisión",
        "Next &raquo;":"Siguiente >",
        "&laquo; Previous":"< Anterior",
        pending:"Pendiente",
        completed:"Completado",
        rejected:"Rechazado",
        address:"Dirección",
        phone:"Teléfono",
        contact_name:"Nombre de Contacto",
};
export default strings;