const strings = {
        format_date: "Fecha",
        client:"Cliente",
        project:"Proyecto",
        name:"Nombre",
        description:"Descripción",
        label:"Concepto",
        amount:"Monto",
        amount_final:"Monto Final",
        amount_paid:"Monto Pagado",
        iva_amount:"Monto con IVA",
        comission:"Comisión",
        "Next &raquo;":"Siguiente >",
        "&laquo; Previous":"< Anterior",
        pending:"Pendiente",
        completed:"Completado",
        rejected:"Rechazado",
        address:"Dirección",
        phone:"Teléfono",
        contact_name:"Nombre de Contacto",
        units:"Unidades",
        unit_price:"Valor Unitario",
        total_comission:"Total con comisión",
        required:'Este campo es requerido',
        delete:"Borrar",
        cancel:"Cancelar",
        client_id:"Client",
        contact_name:"Nombre de contacto",
        phone:"Teléfono",
        email:"Email",
        category:"Categoría",
        file:"Folio",
        forgot:"¿Olvidaste tu contraseña?",
        type:"Tipo",
        cash:"Efectivo",
        transfer:"Transferencia",
        check:"Cheque",
        reference:"Referencia",
        unit_type:"Tipo de unidad",
        provider_id:"Proveedor",
        image:"Imagen",
        client:"Cliente",
        provider_name:"Proveedor",
        total_amount:"Total de deuda",
        total_paid:"Total Pagado",
        provider:"Proveedor",
        status:"Estatus",
        iva:"IVA",
        delete_sure:"¿Estás seguro que quieres borrar este registro?",
        accept:"Aceptar",
        cancel:"Cancelar",
        unit_comission:"Valor Unitario Comisión",
};
export default strings;