name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build Front End
        run: npm install && NODE_ENV=CI npm run build
        working-directory: ./

      - name: FTP Deploy API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: "ftps"
          local-dir: ./
          server-dir: /app/
          exclude: |
            **/vendor/**
            !**/resources/views/vendor/**
            **/node_modules/**

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH command
        run: |
          ssh -o StrictHostKeyChecking=no -p7822 chekogar@chekogarcia.com.mx 'cd taller1100.chekogarcia.com.mx/app && /opt/cpanel/composer/bin/composer install'
