name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build Front End
        run: npm install && NODE_ENV=CI npm run build
        working-directory: ./

      - name: FTP Deploy API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: "ftps"
          local-dir: ./
          server-dir: /app/
          exclude: |
            **/vendor/**
            !/resources/views/vendor/**
            **/node_modules/**
