name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build Front End
        run: npm install && NODE_ENV=CI npm run build
        working-directory: ./
      # - name: Wipe Project Dir
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: rm -rf taller1100.chekogarcia.com.mx/*;
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USERNAME}}
      #     passphrase: ${{secrets.SSH_PASSWORD}}
      #     privateKey: ${{secrets.SSH_PRIVATE_KEY}}
      #     port: ${{secrets.SSH_PORT}}
      - name: FTP Deploy API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: "ftps"
          local-dir: ./
          server-dir: /app/
          exclude: |
            **/vendor/**

      - name: Run Post Deploy Script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /taller1100.chekogarcia.com.mx/app; chmod 755 deploy/deploy.ci.sh; chmod o+x deploy/deploy.ci.sh; ./deploy/deploy.ci.sh; exit;
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSWORD}}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
